language: node_js
node_js:
  - "6.9.1"
env:
  - NODE_ENV=travis
install:
  - npm install
  - gulp gulp-release
branches:
  only:
    - master
cache:
  apt : true
  directories:
    - node_modules
before_deploy: 
  - cd dist    
deploy:
  provider: heroku
  app: demo-chatbots    
  skip_cleanup: true
  api_key:
    secure: "$HEROKU_APP_KEY"
notifications:
  email:
      - kulkarni.mak172@gmail.com
